version: '3.5'
services:
  db:
    build: builds/mysql
    env_file:
      - ./docker.env
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    tty: true
    networks:
      - wordpress-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./docker.env
    ports:
     - 8080:80
    networks:
      - wordpress-network

  wordpress:
    build: builds/wordpress
    ports:
      - 80:80
    volumes:
      - ../../wordpress:/var/www/html
      - ../../src/themes:/var/www/themes
      - ../../src/plugins:/var/www/plugins
    networks:
      - wordpress-network

volumes:
    db_data: {}

networks:
  wordpress-network:
    driver: bridge
