version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - db_data:/var/lib/mysql
    tty: true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
     - PMA_USER=wordpress
     - PMA_PASSWORD=wordpress
     - MYSQL_ROOT_PASSWORD=wordpress
    ports:
     - 127.0.0.1:8080:80

  wordpress:
    image: wordpress:latest
    ports:
      - 127.0.0.1:80:80
    restart: always
    depends_on:
      - db
    links:
      - db
    volumes:
      - ../wordpress:/var/www/html
      - ../themes:/var/www/themes
    networks:
      - wordpress-network

volumes:
    db_data:

networks:
  wordpress-network:
    driver: bridge