version: '3.5'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - db_data:/var/lib/mysql
    tty: true
    networks:
      - wordpress-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
     - 127.0.0.1:8080:80
    networks:
      - wordpress-network

  wordpress:
    image: wordpress:latest
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ../wordpress:/var/www/html
      - ../src/themes:/var/www/themes
      - ../src/plugins:/var/www/plugins
    networks:
      - wordpress-network

volumes:
    db_data: {}

networks:
  wordpress-network:
    name: ${COMPOSE_PROJECT_NAME}
    driver: bridge